version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./api-server/Dockerfile
    command: flask run --host=0.0.0.0
    volumes:
      - ./pipe:/hostpipe
    ports:
      - "50000:5000"

  rabbit:
    build:
      context: .
      dockerfile: ./rabbit/Dockerfile
    command: ./init.sh
    ports:
      - "15672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 15s
      timeout: 30s
      retries: 5

  daemon:
    build:
      context: .
      dockerfile: ./daemon/Dockerfile
    command: >
      sh -c "
          if ! [ -p hostpipe/workerpipe ];
            then mkfifo /hostpipe/workerpipe ;
          fi &&
          python listener.py
      "
    volumes:
      - ./pipe:/hostpipe
    depends_on:
      rabbit:
        condition: service_healthy
